### PR TITLE
sof-soundwire: add known configurations to test UCM files

### PR DESCRIPTION
**Pull request by plbossart**
Configurations from RVP and production devices.

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

### CODE REVIEW

**Comment by perexg** [comment]
Why the module name is (efault)?

````
!!Module: (efault)
        * : 
````

The latest validator also relies on the module name. I replaced this with snd_soc_skl_hda_dsp name in my tree.

**Comment by perexg** [comment]
I merged this (with the updated module names). Thank you.

**Comment by plbossart** [comment]
> Why the module name is (efault)?
> 
> ```
> !!Module: (efault)
>         * : 
> ```
> 
> The latest validator also relies on the module name. I replaced this with snd_soc_skl_hda_dsp name in my tree.

cat /proc/asound/modules 
 0 (efault)

Not sure what's going on here, this seems to happen on all SoundWire platforms. Any pointers to help me figure out why this happens?

**Comment by tiwai** [comment]
On Wed, 24 Jun 2020 17:01:33 +0200,
Pierre-Louis Bossart wrote:
> 
> Not sure what's going on here, this seems to happen on all SoundWire
> platforms. Any pointers to help me figure out why this happens?

The string comes from lib/vsprintf.c, implying that the module->name
pointer is broken.

**Comment by plbossart** [comment]
> On Wed, 24 Jun 2020 17:01:33 +0200, Pierre-Louis Bossart wrote: Not sure what's going on here, this seems to happen on all SoundWire platforms. Any pointers to help me figure out why this happens?
> The string comes from lib/vsprintf.c, implying that the module->name pointer is broken.

I am a bit lost here, is this the same name as what is reported by lsmod/modinfo?

modinfo snd_soc_sof_sdw
filename:       /lib/modules/5.8.0-rc1-test+/kernel/sound/soc/intel/boards/snd-soc-sof-sdw.ko
alias:          platform:sof_sdw
license:        GPL v2
author:         Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
author:         Rander Wang <rander.wang@linux.intel.com>
author:         Bard Liao <yung-chuan.liao@linux.intel.com>
description:    ASoC SoundWire Generic Machine driver
depends:        snd-soc-core,snd,snd-hda-core,snd-soc-hdac-hdmi,soundwire-bus,snd-hda-codec
retpoline:      Y
intree:         Y
name:           snd_soc_sof_sdw
vermagic:       5.8.0-rc1-test+ SMP mod_unload

**Comment by tiwai** [comment]
On Wed, 24 Jun 2020 17:14:27 +0200,
Pierre-Louis Bossart wrote:
> 
> I am a bit lost here, is this the same name as what is reported by lsmod/
> modinfo?

I guess .owner field is missing in card_sof_sdw definition.

**Comment by tiwai** [comment]
Through a quick glance,  the following miss the owner field for Intel in addition to sof_sdw.c
sound/soc/intel/boards/bxt_rt298.c
sound/soc/intel/boards/cml_rt1011_rt5682.c

**Comment by tiwai** [comment]
.. and sound/soc/rockchip/rk3288_hdmi_analog.c

Not sure about sound/soc/sof/nocodec.c.
It might need the owner field, too?

**Comment by plbossart** [comment]
> .. and sound/soc/rockchip/rk3288_hdmi_analog.c
> 
> Not sure about sound/soc/sof/nocodec.c.
> It might need the owner field, too?

Thanks Takashi. I can fix this, but would it make sense to instead add something in the ALSA core that sets the .owner to THIS_MODULE automagically, as done for platform devices?

**Comment by plbossart** [comment]
@perexg fixed now in the SOF tree, the results show

cat /proc/asound/modules 
 0 snd_soc_sof_sdw

**Comment by perexg** [comment]
Thanks. I already changed the ucm-validator config files to use this correct module name.

**Pull request closed without merging**
