### PR TITLE
ucm-validator: add Qualcomm RB5 Robotics Platform

### PR DESCRIPTION
**Pull request by lumag**
Add support to "The Qualcomm Robotics RB5 Platform"

Signed-off-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
[DB: change patch to the config, add module information]
Signed-off-by: Dmitry Baryshkov <dbaryshkov@gmail.com>

### CODE REVIEW

**Comment by lumag** [comment]
This replaces #14 to provide updated paths.

**Comment by lumag** [comment]
@perexg ping for the RB5 tests

**Comment by perexg** [comment]
Merged in 13fa9dec5b4151a393b15bccc8f8a17157fb5d7f . The tests are passing now.

**Comment by lumag** [comment]
Thank you!

**Pull request closed without merging**
